# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-19 05:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_of_the_task',
            field=models.DateField(default=datetime.date(2019, 5, 19), help_text='Day of the task', verbose_name='Day of the task'),
        ),
        migrations.AddField(
            model_name='todo',
            name='end_time_of_task',
            field=models.TimeField(default=datetime.time(10, 33, 29, 586137), help_text='Final time', verbose_name='Final time'),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_time_of_task',
            field=models.TimeField(default=datetime.time(10, 33, 29, 586137), help_text='Starting time', verbose_name='Starting time'),
        ),
    ]
